import HeaderPage from "@/components/UI/header/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/UI/footer/footer";
import { GlobalProvider } from "./GlobalProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
       <body className={`${inter.variable}`}>
        <GlobalProvider>
          <HeaderPage />
          {children}
          <Footer/>
        </GlobalProvider>
      </body>
    </html>
  );
}
